In [9]:
import itk
import numpy as np

print("A numpy array (arr) and itkImage (img) set to identity.")
arr = np.eye(3,3)
img = itk.GetImageFromArray(arr)

print("Using an itkImage in np.where statement produces unexpected results...")
print("   Array where arr[i,j]==0 change to a 2 =", np.where(arr==0,2,arr))
print("   itkImage where img[i,j]==0 change to a 2 =", np.where(img==0,2,img))

A numpy array (arr) and itkImage (img) set to identity.
Using an itkImage in np.where statement produces unexpected results...
   Array where arr[i,j]==0 change to a 2 = [[1. 2. 2.]
 [2. 1. 2.]
 [2. 2. 1.]]
   itkImage where img[i,j]==0 change to a 2 = [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
print("The test itkImage==<value> appears to always return false?")

arr = np.zeros([3,3])
img = itk.GetImageFromArray(arr)
print("   Given arr=0, using np.where to change any instance of arr[i,j]==0 to a 2 =", np.where(arr==0,2,arr))
print("   Given img=0, using np.where to change any instance of img[i,j]==0 to a 2 =", np.where(img==0,2,img))

The test itkImage==<value> appears to always return false?
   Given arr=0, using np.where to change any instance of arr[i,j]==0 to a 2 = [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
   Given img=0, using np.where to change any instance of img[i,j]==0 to a 2 = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
