In [9]:
import os
from random import sample
import datetime
import numpy as np

from ipywidgets import IntProgress
from IPython.display import display, HTML

import girder_client
import matplotlib.pyplot as plt
import pandas as pd

import torch
import torchmetrics
from torch.utils.tensorboard import SummaryWriter
from pytorch_unet import UNet, UNet_rect_kernels
from dataset_loader import DataAugmentor
from glob import glob

In [7]:
local_data_folder = r"/home/nick/dev/SaggitalSpineSegmentation_Data"
validation_data_arrays = sorted(glob(os.path.join(local_data_folder, 'DataArrays/[q]*')))

In [8]:
validation_data_arrays

['/home/nick/dev/SaggitalSpineSegmentation_Data/DataArrays/q000_segmentation.npy',
 '/home/nick/dev/SaggitalSpineSegmentation_Data/DataArrays/q000_ultrasound.npy',
 '/home/nick/dev/SaggitalSpineSegmentation_Data/DataArrays/q001_segmentation.npy',
 '/home/nick/dev/SaggitalSpineSegmentation_Data/DataArrays/q001_ultrasound.npy',
 '/home/nick/dev/SaggitalSpineSegmentation_Data/DataArrays/q002_segmentation.npy',
 '/home/nick/dev/SaggitalSpineSegmentation_Data/DataArrays/q002_ultrasound.npy',
 '/home/nick/dev/SaggitalSpineSegmentation_Data/DataArrays/q003_segmentation.npy',
 '/home/nick/dev/SaggitalSpineSegmentation_Data/DataArrays/q003_ultrasound.npy',
 '/home/nick/dev/SaggitalSpineSegmentation_Data/DataArrays/q004_segmentation.npy',
 '/home/nick/dev/SaggitalSpineSegmentation_Data/DataArrays/q004_ultrasound.npy',
 '/home/nick/dev/SaggitalSpineSegmentation_Data/DataArrays/q005_segmentation.npy',
 '/home/nick/dev/SaggitalSpineSegmentation_Data/DataArrays/q005_ultrasound.npy',
 '/home/nick/dev

In [12]:
msd_path = os.path.join(local_data_folder, 'SavedModels/PyTorchSagittalSpineSegmentationStudy_model-7_2021-07-30_12-55-54.msd')
model = UNet(128,2)
model.load_state_dict(torch.load(msd_path))

<All keys matched successfully>

In [28]:
val_prediction = torch.load(os.path.join(local_data_folder, 'PredictionsValidation/2021-07-30_12-55-54_prediction_q007_ultrasound.npy'))

In [29]:
print(val_prediction.size())
val_prediction = torch.nn.functional.softmax(val_prediction, dim=1)
print(val_prediction.size())
val_prediction = val_prediction.argmax(dim=1)
torch.unique(val_prediction)

torch.Size([446, 2, 128, 128])
torch.Size([446, 2, 128, 128])


tensor([0], device='cuda:0')

In [20]:
val_ultrasound = np.load(os.path.join(local_data_folder, 'DataArrays/q007_ultrasound.npy'))
val_groundtruth = np.load(os.path.join(local_data_folder, 'DataArrays/q007_segmentation.npy'))
print(np.shape(val_ultrasound), np.shape(val_groundtruth))

(446, 128, 128, 1) (446, 128, 128, 1)


In [34]:
val_predictions = sorted(glob(os.path.join(local_data_folder, 'PredictionsValidation/2021-08-04_12-42-32*')))
val_predictions

['/home/nick/dev/SaggitalSpineSegmentation_Data/PredictionsValidation/2021-08-04_12-42-32_prediction_q000_ultrasound.npy',
 '/home/nick/dev/SaggitalSpineSegmentation_Data/PredictionsValidation/2021-08-04_12-42-32_prediction_q001_ultrasound.npy',
 '/home/nick/dev/SaggitalSpineSegmentation_Data/PredictionsValidation/2021-08-04_12-42-32_prediction_q002_ultrasound.npy',
 '/home/nick/dev/SaggitalSpineSegmentation_Data/PredictionsValidation/2021-08-04_12-42-32_prediction_q003_ultrasound.npy',
 '/home/nick/dev/SaggitalSpineSegmentation_Data/PredictionsValidation/2021-08-04_12-42-32_prediction_q004_ultrasound.npy',
 '/home/nick/dev/SaggitalSpineSegmentation_Data/PredictionsValidation/2021-08-04_12-42-32_prediction_q005_ultrasound.npy',
 '/home/nick/dev/SaggitalSpineSegmentation_Data/PredictionsValidation/2021-08-04_12-42-32_prediction_q006_ultrasound.npy',
 '/home/nick/dev/SaggitalSpineSegmentation_Data/PredictionsValidation/2021-08-04_12-42-32_prediction_q007_ultrasound.npy']

In [35]:
for vp in val_predictions:
    val_prediction = val_prediction = torch.load(vp)
    print(val_prediction.size())
    val_prediction = torch.nn.functional.softmax(val_prediction, dim=1)
    print(val_prediction.size())
    val_prediction = val_prediction.argmax(dim=1)
    print(torch.unique(val_prediction))

torch.Size([523, 2, 128, 128])
torch.Size([523, 2, 128, 128])
tensor([0], device='cuda:0')
torch.Size([355, 2, 128, 128])
torch.Size([355, 2, 128, 128])
tensor([0, 1], device='cuda:0')
torch.Size([477, 2, 128, 128])
torch.Size([477, 2, 128, 128])
tensor([0], device='cuda:0')
torch.Size([453, 2, 128, 128])
torch.Size([453, 2, 128, 128])
tensor([0], device='cuda:0')
torch.Size([289, 2, 128, 128])
torch.Size([289, 2, 128, 128])
tensor([0], device='cuda:0')
torch.Size([387, 2, 128, 128])
torch.Size([387, 2, 128, 128])
tensor([0], device='cuda:0')
torch.Size([360, 2, 128, 128])
torch.Size([360, 2, 128, 128])
tensor([0], device='cuda:0')
torch.Size([446, 2, 128, 128])
torch.Size([446, 2, 128, 128])
tensor([0], device='cuda:0')
